on: [push]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    name: Testing auto log committer action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump Data
        run: echo ${{ toJson(github) }}
      - name: Install moreutils
        run: sudo apt-get install moreutils
      - name: Run auto log commiter action
        uses: ./
        with:
            commit_message: ${{ steps.hello.outputs.time }}
            branch: ${{ github.head_ref }}