on: [push]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    name: Testing auto log committer action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump Data
        env:
            DATA: ${{ github.event }}
        run: echo ${DATA}
      - name: Show Popularity
        run: |
            STARS=$(jq --raw-output .repository.stargazers "${{ github.event_path }}")
            FORKS=$(jq --raw-output .repository.forks "${{ github.event_path }}")
            echo "${{ github.repository }} has $STARS stars and $FORKS forks"
      - name: Install moreutils
        run: sudo apt-get install moreutils
      - name: Run auto log commiter action
        uses: ./
        with:
            commit_message: ${{ steps.hello.outputs.time }}
            branch: ${{ github.head_ref }}