on: [push]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    name: Testing auto log committer action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install moreutils
        run: sudo apt-get install moreutils
      - name: Run auto log commiter action
        uses: ./
        with:
            # commit_message: ${{ github.event.head_commit.author.username }} ${{ github.event.head_commit.message }}
            branch: ${{ github.head_ref }}
            bot_user_name: Tripheo0412
            bot_user_email: tripheo0412@gmail.com