on: [push]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    name: Testing auto log committer action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install moreutils
        run: sudo apt-get install moreutils
      - name: Run auto log commiter action
        env:
            COMMIT_MESSAGE: ${{ toJson(github.event.head_commit.message) }}
            COMMIT_AUTHOR: ${{ toJson(github.event.head_commit.committer.username) }}
        uses: ./
        with:
            commit_message: ${{ toJson(github.event.head_commit.committer.username) }} ${{ github.event.head_commit.message }}
            branch: ${{ github.head_ref }}