on: [push]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    name: Testing auto log committer action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install moreutils
        run: sudo apt-get install moreutils
      - name: Run auto log commiter action
        uses: ./
        with:
            branch: ${{ github.head_ref }}
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"