on: [push]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    name: Testing auto log committer action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB.CONTEXT" | jq '.head_commit'
      - name: Install moreutils
        run: sudo apt-get install moreutils
      - name: Run auto log commiter action
        uses: ./
        with:
            commit_user_name: ${{ github.head_commit.committer.username }}
            commit_user_email: ${{ github.head_commit.committer.email }}
            commit_message: Auto log commiter
            branch: ${{ github.head_ref }}
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"